/*
 * (c) Copyright 2005-2015 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/repository/Repository.e.vm.java
 */
package com.ankushn.demo.repository;

import javax.inject.Named;
import javax.inject.Singleton;

import com.ankushn.demo.domain.Dbuser;
import com.ankushn.demo.repository.support.GenericRepository;

/**
 * {@link GenericRepository} for {@link Dbuser} 
 */
@Named
@Singleton
public class DbuserRepository extends GenericRepository<Dbuser, Integer> {

    public DbuserRepository() {
        super(Dbuser.class);
    }

    @Override
    public Dbuser getNew() {
        return new Dbuser();
    }

    @Override
    public Dbuser getNewWithDefaults() {
        return getNew().withDefaults();
    }
}