/*
 * (c) Copyright 2005-2015 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/repository/Repository.e.vm.java
 */
package com.ankushn.demo.repository;

import javax.inject.Named;
import javax.inject.Singleton;

import org.hibernate.LazyInitializationException;
import org.springframework.transaction.annotation.Transactional;

import com.ankushn.demo.domain.Document;
import com.ankushn.demo.repository.support.GenericRepository;

/**
 * {@link GenericRepository} for {@link Document} 
 */
@Named
@Singleton
public class DocumentRepository extends GenericRepository<Document, String> {

    public DocumentRepository() {
        super(Document.class);
    }

    @Override
    public Document getNew() {
        return new Document();
    }

    @Override
    public Document getNewWithDefaults() {
        return getNew().withDefaults();
    }

    /**
     * Safe way to load the documentBinary content. 
     */
    @Transactional(readOnly = true)
    public byte[] getDocumentBinary(Document document) {
        if (!document.isIdSet()) {
            return document.getDocumentBinary();
        }

        try {
            return document.getDocumentBinary();
        } catch (LazyInitializationException lie) { // _HACK_ as we still rely on hibernate here
            return get(document).getDocumentBinary();
        }
    }
}