/*
 * (c) Copyright 2005-2015 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/pages/entity/SearchPage.e.vm.java
 */
package com.ankushn.demo.web.selenium.page.dbuser;

import com.ankushn.demo.web.selenium.support.Page;
import com.ankushn.demo.web.selenium.support.elements.Autocomplete;
import com.ankushn.demo.web.selenium.support.elements.CustomWebElement;
import com.ankushn.demo.web.selenium.support.elements.EntityAction;
import com.ankushn.demo.web.selenium.support.elements.Messages;
import com.ankushn.demo.web.selenium.support.elements.OrderBy;
import com.ankushn.demo.web.selenium.support.elements.SearchForm;
import com.ankushn.demo.web.selenium.support.elements.StringRange;
import com.ankushn.demo.web.selenium.support.elements.Table;

@Page
public class DbuserSearch {
    public Table table;
    public EntityAction entity;
    public Messages messages;
    public DbuserSearchOrders orders;
    public DbuserSearchForm form;

    public static class DbuserSearchOrders extends CustomWebElement {
        public OrderBy username = new OrderBy("dbuser_username");
        public OrderBy createdBy = new OrderBy("dbuser_createdBy");
        public OrderBy createdDate = new OrderBy("dbuser_createdDate");
    }

    public static class DbuserSearchForm extends SearchForm {
        public Autocomplete username = new Autocomplete("form:username");
        public Autocomplete createdBy = new Autocomplete("form:createdBy");
        public StringRange createdDate = new StringRange("form:createdDate");
    }
}