/*
 * (c) Copyright 2005-2015 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/pages/entity/SearchPage.e.vm.java
 */
package com.ankushn.demo.web.selenium.page.book;

import com.ankushn.demo.web.selenium.support.Page;
import com.ankushn.demo.web.selenium.support.elements.Autocomplete;
import com.ankushn.demo.web.selenium.support.elements.CustomWebElement;
import com.ankushn.demo.web.selenium.support.elements.EntityAction;
import com.ankushn.demo.web.selenium.support.elements.Messages;
import com.ankushn.demo.web.selenium.support.elements.OrderBy;
import com.ankushn.demo.web.selenium.support.elements.SearchForm;
import com.ankushn.demo.web.selenium.support.elements.StringRange;
import com.ankushn.demo.web.selenium.support.elements.Table;

@Page
public class BookSearch {
    public Table table;
    public EntityAction entity;
    public Messages messages;
    public BookSearchOrders orders;
    public BookSearchForm form;

    public static class BookSearchOrders extends CustomWebElement {
        public OrderBy accountId = new OrderBy("book_accountId");
        public OrderBy title = new OrderBy("book_title");
        public OrderBy numberOfPages = new OrderBy("book_numberOfPages");
    }

    public static class BookSearchForm extends SearchForm {
        public Autocomplete title = new Autocomplete("form:title");
        public StringRange numberOfPages = new StringRange("form:numberOfPages");
        public Autocomplete account = new Autocomplete("form:accountSelector");
    }
}