/*
 * (c) Copyright 2005-2015 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/EditForm.e.vm.java
 */
package com.ankushn.demo.web.domain;

import javax.annotation.PostConstruct;
import javax.inject.Inject;
import javax.inject.Named;

import com.ankushn.demo.domain.Account;
import com.ankushn.demo.domain.Account_;
import com.ankushn.demo.domain.Address;
import com.ankushn.demo.domain.Role;
import com.ankushn.demo.repository.AccountRepository;
import com.ankushn.demo.web.domain.support.GenericEditForm;
import com.ankushn.demo.web.domain.support.GenericToManyAssociation;
import com.ankushn.demo.web.domain.support.GenericToOneAssociation;
import com.ankushn.demo.web.faces.ConversationContextScoped;
import com.ankushn.demo.web.util.TabBean;

/**
 * View Helper/Controller to edit {@link Account}.
 */
@Named
@ConversationContextScoped
public class AccountEditForm extends GenericEditForm<Account, String> {
    @Inject
    protected AccountController accountController;
    @Inject
    protected AddressController addressController;
    protected GenericToOneAssociation<Address, Integer> address;
    @Inject
    protected RoleController roleController;
    protected GenericToManyAssociation<Role, Integer> roles;
    protected TabBean tabBean = new TabBean();

    @Inject
    public AccountEditForm(AccountRepository accountRepository, AccountGraphLoader accountGraphLoader) {
        super(accountRepository, accountGraphLoader);
    }

    /**
     * View helper to store the x-to-many associations tab's index. 
     */
    @Override
    public TabBean getTabBean() {
        return tabBean;
    }

    /**
     * The entity to edit/view.
     */
    public Account getAccount() {
        return getEntity();
    }

    public String print() {
        return accountController.print(getAccount());
    }

    @PostConstruct
    void setupAddressActions() {
        address = new GenericToOneAssociation<Address, Integer>(addressController, Account_.address) {
            @Override
            protected Address get() {
                return getAccount().getAddress();
            }

            @Override
            protected void set(Address address) {
                getAccount().setAddress(address);
            }
        };
    }

    public GenericToOneAssociation<Address, Integer> getAddress() {
        return address;
    }

    @PostConstruct
    void setupRolesActions() {
        roles = new GenericToManyAssociation<Role, Integer>(getAccount().getRoles(), roleController, Account_.roles) {
            @Override
            protected void remove(Role role) {
                getAccount().removeRole(role);
            }

            @Override
            protected void add(Role role) {
                // add the object only to the role side of the relation 
                getAccount().getRoles().add(role);
            }
        };
    }

    public GenericToManyAssociation<Role, Integer> getRoles() {
        return roles;
    }
}
