/*
 * (c) Copyright 2005-2015 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/ExcelExporter.e.vm.java
 */
package com.ankushn.demo.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import com.ankushn.demo.domain.Book;
import com.ankushn.demo.web.domain.support.GenericExcelExporter;
import com.ankushn.demo.web.faces.ConversationContextScoped;

/**
 * Exports to excel document {@link Book} search criteria and result. 
 */
@Named
@ConversationContextScoped
public class BookExcelExporter extends GenericExcelExporter<Book> {
    @Inject
    protected BookSearchForm sf;

    public BookExcelExporter() {
        super("book_title", "book_numberOfPages");
    }

    @Override
    protected void fillResultItem(int row, Book item) {
        int col = 0;
        setValue(row, col++, item.getTitle());
        setValue(row, col++, item.getNumberOfPages());
    }

    @Override
    public void fillSearchCriteria(int row) {
        useCriteriaSheet();

        setSelectedEntities(row++, 0, "book_account", sf.getAccountSelector().getSelected());
        setSelector(row++, 0, "book_title", sf.getTitleSelector());
        setRangeNumber(row++, 0, "book_numberOfPages", sf.getNumberOfPagesRange());
    }
}