/*
 * (c) Copyright 2005-2015 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/LazyDataModel.e.vm.java
 */
package com.ankushn.demo.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import org.primefaces.model.LazyDataModel;

import com.ankushn.demo.domain.Book;
import com.ankushn.demo.repository.BookRepository;
import com.ankushn.demo.web.domain.support.GenericLazyDataModel;
import com.ankushn.demo.web.faces.ConversationContextScoped;

/**
 * Provide PrimeFaces {@link LazyDataModel} for {@link Book}
 */
@Named
@ConversationContextScoped
public class BookLazyDataModel extends GenericLazyDataModel<Book, Integer, BookSearchForm> {
    private static final long serialVersionUID = 1L;

    @Inject
    public BookLazyDataModel(BookRepository bookRepository, BookController bookController, BookSearchForm bookSearchForm, BookExcelExporter bookExcelExporter) {
        super(bookRepository, bookController, bookSearchForm, bookExcelExporter);
    }
}