/*
 * (c) Copyright 2005-2015 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/LazyDataModel.e.vm.java
 */
package com.ankushn.demo.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import org.primefaces.model.LazyDataModel;

import com.ankushn.demo.domain.Dbuser;
import com.ankushn.demo.repository.DbuserRepository;
import com.ankushn.demo.web.domain.support.GenericLazyDataModel;
import com.ankushn.demo.web.faces.ConversationContextScoped;

/**
 * Provide PrimeFaces {@link LazyDataModel} for {@link Dbuser}
 */
@Named
@ConversationContextScoped
public class DbuserLazyDataModel extends GenericLazyDataModel<Dbuser, Integer, DbuserSearchForm> {
    private static final long serialVersionUID = 1L;

    @Inject
    public DbuserLazyDataModel(DbuserRepository dbuserRepository, DbuserController dbuserController, DbuserSearchForm dbuserSearchForm,
            DbuserExcelExporter dbuserExcelExporter) {
        super(dbuserRepository, dbuserController, dbuserSearchForm, dbuserExcelExporter);
    }
}