/*
 * (c) Copyright 2005-2015 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/SearchForm.e.vm.java
 */
package com.ankushn.demo.web.domain;

import static com.ankushn.demo.repository.support.PropertySelector.newPropertySelector;

import javax.inject.Named;

import com.ankushn.demo.domain.Account;
import com.ankushn.demo.domain.Document;
import com.ankushn.demo.domain.Document_;
import com.ankushn.demo.repository.support.PropertySelector;
import com.ankushn.demo.repository.support.SearchParameters;
import com.ankushn.demo.web.domain.support.GenericSearchForm;
import com.ankushn.demo.web.faces.ConversationContextScoped;

/**
 * View Helper to search {@link Document}.
 * It exposes a {@link Document} instance so it can be used in search by-example-query.
 */
@Named
@ConversationContextScoped
public class DocumentSearchForm extends GenericSearchForm<Document, String, DocumentSearchForm> {
    private static final long serialVersionUID = 1L;
    protected Document document = new Document();
    protected PropertySelector<Document, Account> accountSelector = newPropertySelector(Document_.account);

    public Document getDocument() {
        return document;
    }

    @Override
    protected Document getEntity() {
        return getDocument();
    }

    @Override
    public DocumentSearchForm newInstance() {
        return new DocumentSearchForm();
    }

    @Override
    public SearchParameters toSearchParameters() {
        SearchParameters sp = searchParameters();
        sp.property(accountSelector);
        return sp;
    }

    @Override
    public void resetWithOther(DocumentSearchForm other) {
        this.document = other.getDocument();
        this.accountSelector = other.getAccountSelector();
    }

    // Relation selectors
    public PropertySelector<Document, Account> getAccountSelector() {
        return accountSelector;
    }
}
