/*
 * (c) Copyright 2005-2015 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/EditForm.e.vm.java
 */
package com.ankushn.demo.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import com.ankushn.demo.domain.Role;
import com.ankushn.demo.repository.RoleRepository;
import com.ankushn.demo.web.domain.support.GenericEditForm;
import com.ankushn.demo.web.faces.ConversationContextScoped;

/**
 * View Helper/Controller to edit {@link Role}.
 */
@Named
@ConversationContextScoped
public class RoleEditForm extends GenericEditForm<Role, Integer> {
    @Inject
    protected RoleController roleController;

    @Inject
    public RoleEditForm(RoleRepository roleRepository) {
        super(roleRepository);
    }

    /**
     * The entity to edit/view.
     */
    public Role getRole() {
        return getEntity();
    }

    public String print() {
        return roleController.print(getRole());
    }
}
