/*
 * (c) Copyright 2005-2015 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/test/java/domain/ModelTest.e.vm.java
 */
package com.ankushn.demo.domain;

import static org.fest.assertions.Assertions.assertThat;

import java.io.*;
import java.util.*;

import org.junit.Test;

import com.ankushn.demo.util.ValueGenerator;

/**
 * Basic tests for Dbuser
 */
@SuppressWarnings("unused")
public class DbuserTest {

    // test unique primary key
    @Test
    public void newInstanceHasNoPrimaryKey() {
        Dbuser model = new Dbuser();
        assertThat(model.isIdSet()).isFalse();
    }

    @Test
    public void isIdSetReturnsTrue() {
        Dbuser model = new Dbuser();
        model.setId(ValueGenerator.getUniqueInteger());
        assertThat(model.getId()).isNotNull();
        assertThat(model.isIdSet()).isTrue();
    }

    /*
     public void equalsUsingPk() {
     Dbuser model1 = new Dbuser();
     Dbuser model2 = new Dbuser();

     Integer id = ValueGenerator.getUniqueInteger();
     model1.setId(id);
     model2.setId(id);

     model1.setUsername("a");
     model2.setUsername("a");

     model1.setCreatedBy("a");
     model2.setCreatedBy("a");

     model1.setCreatedDate(new Date());
     model2.setCreatedDate(new Date());
     assertThat(model1.isIdSet()).isTrue();
     assertThat(model2.isIdSet()).isTrue();
     assertThat(model1.hashCode()).isEqualTo(model2.hashCode());
     assertThat(model1).isEqualTo(model2);
     assertThat(model2).isEqualTo(model1);
     }
     */
}