/*
 * (c) Copyright 2005-2015 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/pages/entity/SearchPage.e.vm.java
 */
package com.ankushn.demo.web.selenium.page.account;

import com.ankushn.demo.web.selenium.support.Page;
import com.ankushn.demo.web.selenium.support.elements.Autocomplete;
import com.ankushn.demo.web.selenium.support.elements.CustomWebElement;
import com.ankushn.demo.web.selenium.support.elements.EntityAction;
import com.ankushn.demo.web.selenium.support.elements.ManyBooleans;
import com.ankushn.demo.web.selenium.support.elements.Messages;
import com.ankushn.demo.web.selenium.support.elements.OrderBy;
import com.ankushn.demo.web.selenium.support.elements.SearchForm;
import com.ankushn.demo.web.selenium.support.elements.StringRange;
import com.ankushn.demo.web.selenium.support.elements.Table;

@Page
public class AccountSearch {
    public Table table;
    public EntityAction entity;
    public Messages messages;
    public AccountSearchOrders orders;
    public AccountSearchForm form;

    public static class AccountSearchOrders extends CustomWebElement {
        public OrderBy login = new OrderBy("account_login");
        public OrderBy password = new OrderBy("account_password");
        public OrderBy email = new OrderBy("account_email");
        public OrderBy isEnabled = new OrderBy("account_isEnabled");
        public OrderBy civility = new OrderBy("account_civility");
        public OrderBy firstName = new OrderBy("account_firstName");
        public OrderBy lastName = new OrderBy("account_lastName");
        public OrderBy birthDate = new OrderBy("account_birthDate");
        public OrderBy description = new OrderBy("account_description");
        public OrderBy addressId = new OrderBy("account_addressId");
    }

    public static class AccountSearchForm extends SearchForm {
        public Autocomplete login = new Autocomplete("form:login");
        public Autocomplete password = new Autocomplete("form:password");
        public Autocomplete email = new Autocomplete("form:email");
        public ManyBooleans isEnabled = new ManyBooleans("form:isEnabled");
        public Autocomplete civility = new Autocomplete("form:civility");
        public Autocomplete firstName = new Autocomplete("form:firstName");
        public Autocomplete lastName = new Autocomplete("form:lastName");
        public StringRange birthDate = new StringRange("form:birthDate");
        public Autocomplete description = new Autocomplete("form:description");
        public Autocomplete address = new Autocomplete("form:addressSelector");
        public Autocomplete roles = new Autocomplete("form:rolesSelector");
    }
}